### ISSUE TITLE
Add the ability to edit things

### ISSUE THREAD

**Issue by grishiit** [jerameel/sushi#10]
This is the most good-looking FOSS finance management app I've ever seen, but it doesn't yet have the same great functionality.

Personally, I really miss the ability to edit all sorts of things, from wallet names to transaction details. It would be great if you could add that

**Comment by jerameel** [comment]
Hey, thanks for the feedback. 

I would definitely work on that soon (or if someone else volunteers).

**Comment by jerameel** [comment]
Implemented in [v1.5](https://github.com/jerameel/sushi/releases/tag/v.1.5).
