### ISSUE TITLE
Traslation in Italian

### ISSUE THREAD

**Issue by Philosobrown** [jerameel/sushi#11]
Hi! I would love to help by translating the app in Italian if you want

**Comment by jerameel** [comment]
That would really be great! 

I think you can just follow the pattern how the currency is changed on settings? or if you have something better in mind, PRs are welcome!

**Comment by Philosobrown** [comment]
Unfortunately I've never used react-native, so maybe it'll take a bit of time, otherwise if you could generate a file of strings that need to be translated I'll happily do it!

**Comment by jerameel** [comment]
Oh right, i need to implement localization first in general. I'll let you know if I have that!

**Comment by Philosobrown** [comment]
Of course! As soon as you implement it since the app is pretty minimal (love it!) I'll translate it as quickly as I can!

**Comment by jerameel** [comment]
I have updated the README with regards to the translation. If you could PR the translation, that would be awesome. Or you can just send me a copy here and i'll add it myself. 

@Philosobrown

**Comment by Philosobrown** [comment]
Hi Jerameel!
`// ADD ACCOUNT
  ADD_ACCOUNT: 'Add Account',
  ACCOUNT_NAME: 'Account Name',
  INITIAL_AMOUNT: 'Initial Amount',
`
is "account" used as in "profile" or finance-wise (i.e. bank account, etc.)?
