### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by piurizza** [jerameel/sushi#14]
Hi, thank you for the effort!
I think sushi is a great minimal finance app.
Can you implement a way to export data via csv file for further personal analytics?

**Comment by jerameel** [comment]
Hey @zeratosk, this is a feature i was planning to implement as well. But I might need the calendar filters feature first before this one is implemented.

**Comment by hmrodrigues** [comment]
It would also be cool to have a backup/restore feature for when someone changes his phone.

Also thank you for the app ;)

**Comment by jerameel** [comment]
This has been implemented, but still needs some polishing. Feel free to open new issues if you found anything.
