### ISSUE TITLE
Edit date of transaction and minor changes to label.

### ISSUE THREAD

**Issue by theY2Kbug** [jerameel/sushi#18]
Is it possible to edit the date of an existing transaction that's added? Or rather it would be great if there's an option to add/edit date to a transaction in a future release.  

Also it would be great if you could change the "expenses" and "income” label to "debit" and "credit" respectively.

Great app BTW! Simple and intuitive.

**Comment by jerameel** [comment]
I have updated the texts, thanks for that one. 

with regards to the dates, i think i might need to add another field which is the actual transaction date. As the existing created/updated date fields are for user's reference only

**Comment by jerameel** [comment]
New transaction date logic is included on next build.
