### ISSUE TITLE
Analysis features

### ISSUE THREAD

**Issue by ZestyCat** [jerameel/sushi#21]
Some analysis features would be great to quickly answer questions like:

> how much did i spend on x category this month? (Sum totals by category)

> how does my spending fluctuate month to month? (Time period comparison)

> what are my greatest expenses? (Sort categories by their sum totals)

Also charts would be very very nice but im not sure if that is outside the scope of the project

**Comment by jerameel** [comment]
@ZestyCat Thanks for the suggestions, this is something I'm thinking for a while but not too sure on what charts i should show.

**Comment by lonovpw** [comment]
Please add statistics of income (+), expenses (-) and profit (income minus expense) for all accounts and each category. You can also add charts by days for accounts and categories. It would also be convenient to create subcategories for categories. Thanks.

**Comment by reitenth** [comment]
i just want to be able to see category spending added up.

**Comment by SubhamV** [comment]
Commenting for visibility

**Comment by jerameel** [comment]
I've added this in the master branch, that should be available in the next release. 

Closing this now so we can create more specific issues later.
