### ISSUE TITLE
Adding income

### ISSUE THREAD

**Issue by YZirkind** [jerameel/sushi#32]
I just installed the app and it looks very nice. The only thing I'm confused about is how do I add income?

**Comment by so1der** [comment]
![image](https://user-images.githubusercontent.com/103759422/180598142-9883d584-1af0-4346-a9ad-ad533e666203.png)
Just press the '+' button under 'Amount' entry. You can also create category named 'Income'

**Comment by jerameel** [comment]
Just to add, I've recently changed the wordings from Income/Expenses to Debit/Credit as it more accurately describes Accounting terms. However, i feel like this is confusing as well (not a native English speaker). I'll try to think of a better way to improve UX on this part.
