### ISSUE TITLE
-$infinity bug causes app to crash on launch

### ISSUE THREAD

**Issue by SnakeOverflow** [jerameel/sushi#34]
When the input on a transaction is 310 digits or more, the app will display a -$infinity instead of the amount entered, if the app is then closed and relaunched the app will crash on opening.

2nd minor bug:
At 15 & 16 digits the decimal will change when saving to round to the neatest quater.

In my opinion limiting the input to 14 digits (99trillion) would provide the usability while also fixing the issue.

**Comment by SnakeOverflow** [comment]
Added a screenshot just in case.

![signal-2022-07-22-10-07-46-665-1](https://user-images.githubusercontent.com/109717184/180490037-b2d3d803-e834-45c4-bdab-8e3d573ff80f.png)

**Comment by jerameel** [comment]
Limiting input to 14 digits does not prevent 15 digits or more from appearing (ex. Sum of transactions). 

I'll limit it for now as a temporary fix.
