### ISSUE TITLE
Tracking anti-feature? (F-Droid)

### ISSUE THREAD

**Issue by fohfuu** [jerameel/sushi#37]
I have a concern which I would like clarified.

[PRIVACY_POLICY.md](https://github.com/jerameel/sushi/blob/main/PRIVACY_POLICY.md) describes several kinds of tracking, for example (emphasis mine):

> **If you choose to use my Service, then you agree to the collection and use of information** in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.
> 
> The app does use **third party services** that may collect information used to identify you.

This policy seems to qualify as the [Tracking Anti-Feature on F-Droid](https://f-droid.org/docs/Anti-Features/#Tracking) (again, emphasis mine):

> ### Tracking
> 
> This Anti-Feature is applied to apps that track you and/or report your activity to somewhere, either without your permission or by default (i.e. you’d have to actively seek out an option to disable it).

> Examples of where it would not be applied - any of the above, if the functionality is opt-in (i.e. you are asked before it happens) and disabled by default. **Enabling it should then also require informed consent**, i.e. requiring a privacy policy similar to GDPR, and avoid collecting personal data (PII) as far as possible.

It does seem like users are automatically opted in to tracking.

If this privacy policy is Tracking as described by F-Droid, please update the app to add the appropriate flag.

Sorry if I'm misunderstanding! Just a friendly question.

**Comment by jerameel** [comment]
Hi, I've used a generic template for this one. I'm not knowledgeable in this field so if someone wants to update the Policy that would be better. 

With regards to your concern, if there would be any kind of tracking in the future, you will be notified as it will be stated in the policy. 
> i.e. you are asked before it happens) and disabled by default. Enabling it should then also require informed consent

The code is also open for anyone who wants to check for this kind of concern. 

I'm closing this for now, but if there would be PRs for the policy, it would be welcome. Thanks!
