### ISSUE TITLE
Avast anti-virus flags this app as 'suspicious'

### ISSUE THREAD

**Issue by Dao0fGeek** [jerameel/sushi#39]
Avast anti-virus flags this app as one that is 'suspicious' and may 'harm your device'. Either the code needs to be audited or Avast needs to be informed of a false positive.

**Comment by jerameel** [comment]
Definitely a false positive, the code is open for you to audit.

Also you've created a new account just to comment this "issue" and that seems a bit suspicious in itself.  But if you just really want to help, i believe you can reach out to avast to say that it's false positive. 

Here's a report from virustotal with the AAB release on v1.10
https://www.virustotal.com/gui/file/05dac7356018698c354fbe328effd172372203985ba450abe6254dbcbaa7ee36?nocache=1

**Comment by Dao0fGeek** [comment]
Nothing suspicious.  Just trying to be a "good neighbor" cuz if I'm getting them flagged then other Avast users are too. Just my guess, but Avast may be flagging new updates and installs from F-droid cuz it also flagged OpenCalc and Gurgle which I had installed previously via F-droid - so they may all have been flagged after they updated. I don't have any other explanation. Since virustotal's version of the avast engine doesn't flag it or the others it's probably unique to the android version of Avast's engine, probably updated to flag anything installed outside the GooglePlay store as 'suspicious'.
