### ISSUE TITLE
Add setting where to place currency symbol

### ISSUE THREAD

**Issue by 1412kaito** [jerameel/sushi#46]
I noticed that while using the USD $ symbol, it is placed before (left side) the numbers. But when I tried selecting a couple other currency symbols - I tried IDR/id (as it's my local currency) and a few of the EUR ones - they are placed behind (right side) the numbers.

Especially for the Euro-symbol ones, there are some that have the symbols on the left side 🤔.

I've taken a look at numbro, but there doesn't seem to be any config about the symbol placement. 

Would it be possible to have a setting to allow users to choose where the symbols are placed? 

Thanks!

**Comment by 1412kaito** [comment]
Oh, I just dug a bit deeper and found that in numbro there _**is**_ in fact a way to specify postfix or prefix. 

I'll try to create a issue / PR there to adjust this

**Comment by jerameel** [comment]
For now, it should at least follow the standard format per country/currency. The only config I've modified is the *mantissa* which is defined to 2. If you feel like the default currency format is wrong, you can submit an issue on *numbro*  instead. 

I'm closing this temporarily but happy to reopen this if there's a lot of users that needs this particular issue.

**Comment by 1412kaito** [comment]
I have opened a [PR](https://github.com/BenjaminVanRyseghem/numbro/pull/658) over in numbro specific for my local currency, but I couldn't really get a solid reference material - at least not online - on where the symbols should be placed for my local currency :thinking: 

anyway, thanks for the clarification!
