### ISSUE TITLE
Add other currencies

### ISSUE THREAD

**Issue by Erictheplague** [jerameel/sushi#47]
I notice that there are few currencies options on the app 
Which is not good as Alot of people use this app from different countries and continents like Africa and Cambodia
Please kindly look to add major countries currencies like Nigeria,Ghana , Belarus and Ukraine

**Comment by jerameel** [comment]
Currencies is pulled from *numbro* as they already have some currency data. 

If a currency is missing, you might want to file your issue here. 
https://github.com/BenjaminVanRyseghem/numbro
