### ISSUE TITLE
Adding profiles

### ISSUE THREAD

**Issue by SubhamV** [jerameel/sushi#61]
Would love to have the expenses linked to a profile (online and/or offline). This would help with migration of data if the user switches from one device to another. For offline profiles, we may provide an option to export the expense report, which can be then copied over and imported on the new device.

**Comment by jerameel** [comment]
Offline profiles is on my list already but i multiple accounts works fine as of now. That might be implemented a bit later after other features. 

Online is on a different level, I don't think many users actually want their financial record on the cloud. So there's a lot of security measures involved. It could probably be an entirely new project that allows importing sushi's data.

**Comment by SubhamV** [comment]
Thank you! Yes, offline accounts are good enough :)
