### ISSUE TITLE
Account deletion requests should be verified via password or biometrics

### ISSUE THREAD

**Issue by SubhamV** [jerameel/sushi#62]
Currently, if I try to delete any of my accounts, the app simply asks for confirmation and then deletes it. This might be a security concern. If the deletion requests are paired with some sort of authentication like password, pin, or biometric, it will help protect the account from accidental damages.

**Comment by jerameel** [comment]
I think the confirmation itself is enough since the data is offline anyway.

I might implement encryption and authentication in the future for the data at rest but that would be for another discussion
