### ISSUE TITLE
Add PKR to list of currencies

### ISSUE THREAD

**Issue by aadilayub** [jerameel/sushi#8]
Thanks for making this polished app! I was about to start using it, but noticed that my local currency, the [Pakistani Rupee](https://www.xe.com/currency/pkr-pakistani-rupee/) was missing from the currency picker.

**Comment by jerameel** [comment]
Hey @aadilayub , this project uses numbro internally...

If you can add the currency on numbro that would be better.
https://github.com/BenjaminVanRyseghem/numbro/tree/develop/languages

but i can also add the language config within the project if you send me config.

**Comment by jerameel** [comment]
Closing this for now, will wait for updates on numbro core lib.

**Comment by aadilayub** [comment]
Hi, if you could keep this open that would be great, to help me remember to fix the upstream bug.
